# Generated by Django 3.2.5 on 2021-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210724_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Gujarathi', 'Gujarathi'), ('Urdu', 'Urdu'), ('Kannada', 'Kannada'), ('Odia', 'Odia'), ('Malayalam', 'Malayalam'), ('Punjabi', 'Punjabi'), ('Assamese', 'Assamese'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Indonesian', 'Indonesian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Turkish', 'Turkish'), ('Vietnamese', 'Vietnamese')], default=False, max_length=255),
        ),
    ]
